apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-dashboard
  template:
    metadata:
      labels:
        app: simple-dashboard
    spec:
      containers:
      - name: simple-dashboard
        image: cbcyber/simple-dashboard:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
